version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    depends_on:
      - safebase_db
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@safebase_db:5432/${DB_NAME}

  safebase_db:
    image: postgres:16
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - safebase_db_data:/var/lib/postgresql/data
      - ./sql/safebase.sql:/docker-entrypoint-initdb.d/safebase.sql
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  prod_db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USER_PROD}
      - POSTGRES_PASSWORD=${DB_PASSWORD_PROD}
      - POSTGRES_DB=${DB_NAME_PROD}
    ports:
      - "${DB_PORT_PROD}:5432"
    volumes:
      - prod_db_data:/var/lib/postgresql/data

  dev_db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USER_DEV}
      - POSTGRES_PASSWORD=${DB_PASSWORD_DEV}
      - POSTGRES_DB=${DB_NAME_DEV}
    ports:
      - "${DB_PORT_DEV}:5432"
    volumes:
      - dev_db_data:/var/lib/postgresql/data
      - ./sql/dev_db.sql:/docker-entrypoint-initdb.d/dev_db.sql

  mysql_db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD_MYSQL}
      - MYSQL_DATABASE=${DB_NAME_MYSQL}
      - MYSQL_USER=${DB_USER_MYSQL}
      - MYSQL_PASSWORD=${DB_PASSWORD_MYSQL}
    ports:
      - "${DB_PORT_MYSQL}:3306"
    volumes:
      - mysql_db_data:/var/lib/mysql
      - ./sql/bibliotheque_en_ligne.sql:/docker-entrypoint-initdb.d/bibliotheque_en_ligne.sql

volumes:
  safebase_db_data:
  prod_db_data:
  dev_db_data:
  mysql_db_data: