name: Docker CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx (needed to build Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 3. Build the backend Docker image
      - name: Build backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false # We don't push the image, just build it

      # 4. Build the frontend Docker image
      - name: Build frontend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false # We don't push the image, just build it

      # 5. Install Go (needed for running Go tests)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      # # 6. Run backend tests
      # - name: Run backend tests
      #   run: |
      #     cd backend
      #     go test -v ./...
